config/routes.rb
Rails.application.routes.draw do
 
  devise_for :teachers
  # if user authenticated then root is courses page
  authenticated :teacher do
    root 'courses#index', as: :authenticated_root
    resources :courses do
      resources :tests, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :scores, only: [:index, :create, :update, :destroy]
      end
      resources :enrolls, only: [:index, :update, :destroy, :create]
    end
    resources :students
  
  end

  #Change default devise routes
  devise_scope :teacher do
    get '*path' => redirect('/teachers/sign_in')
  end    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enroll.rb
class Enroll < ApplicationRecord
    belongs_to :course
    belongs_to :student

    validates_associated :course  
    validates_associated :student
end

app/controllers/enrolls_controller.rb
class EnrollsController < ApplicationController
  before_action :set_enroll, only: [:show, :edit, :update, :destroy]

  # GET /enrolls
  # GET /enrolls.json
  def index
    @course = params[:course_id]
    @students = Student.left_join_enrolls @course
    puts @students.as_json
  end

  # GET /enrolls/1
  # GET /enrolls/1.json
  def show
  end

  # GET /enrolls/new
  def new
    @enroll = Enroll.new
  end

  # GET /enrolls/1/edit
  def edit
  end

  # POST /course/:course_id/enrolls
  # POST /enrolls.json
  def create
    course = Course.find(params[:course_id])
    student = Student.find_by(dni: params[:student_id])
    @enroll = Enroll.new( student: student, course: course)
    TestCourse.of(course).each do |tc|
      Score.create( student: student, test_id: tc.test_id, value: -2)
    end
    
    respond_to do |format|
      if @enroll.save
        format.html { redirect_to course_enrolls_path(course), notice: 'Enroll was successfully created.' }
        format.json { render :show, status: :created, location: course_enrolls_path(course) }
      else
        format.html { render :new }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolls/1
  # PATCH/PUT /enrolls/1.json
  def update
    respond_to do |format|
      if @enroll.update(enroll_params)
        format.html { redirect_to @enroll, notice: 'Enroll was successfully updated.' }
        format.json { render :show, status: :ok, location: @enroll }
      else
        format.html { render :edit }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolls/1
  # DELETE /enrolls/1.json
  def destroy
    course = Course.find(params[:course_id])
    TestCourse.of(course).each do |tc|
      Score.where( student_id: @enroll.student_id, test_id: tc.test_id).each do |score|
        score.destroy
      end
    end
    @enroll.destroy
    respond_to do |format|
      format.html { redirect_to course_enrolls_path(course), notice: 'Enroll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enroll
      @enroll = Enroll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enroll_params
      params.fetch(:enroll, {})
    end
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/views/enrolls/edit.html.erb
<h1>Editing Enroll</h1>

<%= render 'form', enroll: @enroll %>

<%= link_to 'Show', @enroll, class: "btn" %> |
<%= link_to 'Back', enrolls_path , class: "btn"%>

app/views/enrolls/index.html.erb
<h1>Enrolls</h1>

<table id="enrolls-table" class="display responsive no-wrap" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>DNI</th>
      <th>Legajo</th>
      <th>Enrolled</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name + ' ' + student.last_name %></td>
        <td><%= student.dni %></td>
        <td><%= student.legajo %></td>
        <% if student.id.nil? %>
          <td>
            <%= form_tag("/courses/#{@course}/enrolls", method: "post") do %>
              <%= hidden_field_tag(:student_id, student.dni) %>
              <%= hidden_field_tag(:course_id, @course) %>
              <%= submit_tag("Enroll", class: "btn") %>
            <% end %>
          </td>
        <% else %>
          <td><%= link_to 'Disenroll', "/courses/#{@course}/enrolls/#{student.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', courses_path, class: "btn" %>