config/routes.rb
Rails.application.routes.draw do
 
  devise_for :teachers
  # if user authenticated then root is courses page
  authenticated :teacher do
    root 'courses#index', as: :authenticated_root
    resources :courses do
      resources :tests, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :scores, only: [:index, :create, :update, :destroy]
      end
      resources :enrolls, only: [:index, :update, :destroy, :create]
    end
    resources :students
  
  end

  #Change default devise routes
  devise_scope :teacher do
    get '*path' => redirect('/teachers/sign_in')
  end    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/test_courses_controller.rb
class TestCoursesController < ApplicationController
  before_action :set_test_course, only: [:show, :edit, :update, :destroy]

  # GET /test_courses
  # GET /test_courses.json
  def index
    @test_courses = TestCourse.all
  end

  # GET /test_courses/1
  # GET /test_courses/1.json
  def show
  end

  # GET /test_courses/new
  def new
    @test_course = TestCourse.new
  end

  # GET /test_courses/1/edit
  def edit
  end

  # POST /test_courses
  # POST /test_courses.json
  def create
    @test_course = TestCourse.new(test_course_params)

    respond_to do |format|
      if @test_course.save
        format.html { redirect_to @test_course, notice: 'Test course was successfully created.' }
        format.json { render :show, status: :created, location: @test_course }
      else
        format.html { render :new }
        format.json { render json: @test_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_courses/1
  # PATCH/PUT /test_courses/1.json
  def update
    respond_to do |format|
      if @test_course.update(test_course_params)
        format.html { redirect_to @test_course, notice: 'Test course was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_course }
      else
        format.html { render :edit }
        format.json { render json: @test_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_courses/1
  # DELETE /test_courses/1.json
  def destroy
    @test_course.destroy
    respond_to do |format|
      format.html { redirect_to test_courses_url, notice: 'Test course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_course
      @test_course = TestCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_course_params
      params.fetch(:test_course, {})
    end
end

app/helpers/test_courses_helper.rb
module TestCoursesHelper
end

app/views/test_courses/_form.html.erb
<%= form_with(model: test_course, local: true) do |form| %>
  <% if test_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_course.errors.count, "error") %> prohibited this test_course from being saved:</h2>

      <ul>
      <% test_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/test_courses/edit.html.erb
<h1>Editing Test Course</h1>

<%= render 'form', test_course: @test_course %>

<%= link_to 'Show', @test_course , class: "btn"%> |
<%= link_to 'Back', test_courses_path , class: "btn"%>

app/views/test_courses/index.html.erb
<h1>Test Courses</h1>

<table id="enrolls-table" class="display responsive no-wrap" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_courses.each do |test_course| %>
      <tr>
        <td><%= link_to 'Show', test_course %><%= fa_icon "pencil" , class: "table-icon"%></td>
        <td><%= link_to 'Edit', edit_test_course_path(test_course) %><%= fa_icon "pencil" , class: "table-icon"%></td>
        <td><%= link_to 'Destroy', test_course, method: :delete, data: { confirm: 'Are you sure?' } %><%= fa_icon "trash" , class: "table-icon"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Course', new_test_course_path , class: "btn"%>

app/views/test_courses/new.html.erb
<h1>New Test Course</h1>

<%= render 'form', test_course: @test_course %>

<%= link_to 'Back', test_courses_path , class: "btn"%>

app/views/test_courses/show.html.erb
<%= link_to 'Edit', edit_test_course_path(@test_course) , class: "btn"%> |
<%= link_to 'Back', test_courses_path , class: "btn"%>