config/routes.rb
Rails.application.routes.draw do
 
  devise_for :teachers
  # if user authenticated then root is courses page
  authenticated :teacher do
    root 'courses#index', as: :authenticated_root
    resources :courses do
      resources :tests, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :scores, only: [:index, :create, :update, :destroy]
      end
      resources :enrolls, only: [:index, :update, :destroy, :create]
    end
    resources :students
  
  end

  #Change default devise routes
  devise_scope :teacher do
    get '*path' => redirect('/teachers/sign_in')
  end    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
			<ul class="nav navbar-nav navbar-right">
        <% if teacher_signed_in? %>
            <li><%= link_to "Sign out", destroy_teacher_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to('Sign in', new_teacher_session_path) %></li>
            <li><%= link_to('Sign up', new_teacher_registration_path) %></li>
        <% end %>
			</ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if teacher_signed_in? %>
    <li><%= link_to 'Courses', courses_path %></li>
    <li><%= link_to 'Students', students_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nito" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Nito" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>